const API_URL =
  import.meta.env.VITE_API_URL ||
  "http://localhost:5001/api";

/* =========================================================
   COMMON API RESPONSE TYPES
========================================================= */

export type ApiResponse<T = unknown> = {
  success?: boolean;
  message?: string;
  [key: string]: unknown;
};

/* =========================================================
   COMMON REQUEST
========================================================= */

async function request<T = any>(
  endpoint: string,
  options: RequestInit = {}
): Promise<T> {
  const res = await fetch(`${API_URL}${endpoint}`, {
    ...options,
    credentials: "include",
    headers:
      options.body instanceof FormData
        ? {
            ...options.headers,
          }
        : {
            "Content-Type": "application/json",
            ...options.headers,
          },
  });

  let data: any = null;

  try {
    data = await res.json();
  } catch {
    data = null;
  }

  if (!res.ok) {
    throw new Error(
      data?.message || "Something went wrong"
    );
  }

  return data as T;
}

/* =========================================================
   DISCOUNT TYPES
========================================================= */

export type DiscountType =
  | "SEASONAL"
  | "COUPON"
  | "CUSTOMER";

export type DiscountTarget =
  | "PRODUCT"
  | "CATEGORY"
  | "CART"
  | "CUSTOMER";

export type DiscountKind =
  | "percent"
  | "flat";

/* =========================================================
   DISCOUNT PAYLOAD
========================================================= */

export interface DiscountPayload {
  name?: string | null;

  /*
   * IMPORTANT:
   *
   * Coupon codes are generated by the backend.
   *
   * Therefore the frontend does NOT need to send
   * a code when creating a COUPON.
   *
   * Kept optional here so existing code remains
   * compatible with the backend response/model.
   */
  code?: string | null;

  type: DiscountType;

  target: DiscountTarget;

  kind: DiscountKind;

  /*
   * Always applies to VA / making charges.
   */
  value: number;

  metal?: "Gold" | "Silver" | null;

  category?: string | null;

  productIds?: string[];

  /*
   * Customer-specific discounts.
   */
  userId?: string | null;

  startDate?: string | null;

  endDate?: string | null;

  usageLimit?: number | null;

  usageCount?: number;

  isActive?: boolean;
}

/* =========================================================
   DISCOUNT RESPONSE
========================================================= */

export type DiscountResponse = {
  success: boolean;

  discount: {
    id: string;
    name?: string | null;
    code?: string | null;
    type: DiscountType;
    target: DiscountTarget;
    kind: DiscountKind;
    value: number;
    metal?: "Gold" | "Silver" | null;
    category?: string | null;
    productIds?: string[];
    userId?: string | null;
    startDate?: string | null;
    endDate?: string | null;
    usageLimit?: number | null;
    usageCount?: number;
    isActive: boolean;
    createdAt: string;
    updatedAt?: string;
    [key: string]: any;
  };

  /*
   * Backend may return the generated coupon separately.
   *
   * Example:
   *
   * couponCode: "NVS-A8F4K2P9"
   */
  couponCode?: string | null;
};

/* =========================================================
   UPLOAD FILE WITH PROGRESS
========================================================= */

function uploadFileWithProgress(
  file: File,
  onProgress?: (progress: number) => void
): Promise<{
  success: boolean;
  url: string;
}> {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();

    xhr.open(
      "POST",
      `${API_URL}/admin/upload`,
      true
    );

    // Admin authentication uses cookies
    xhr.withCredentials = true;

    xhr.upload.onprogress = (event) => {
      if (
        event.lengthComputable &&
        onProgress
      ) {
        const percentage = Math.round(
          (event.loaded / event.total) * 100
        );

        onProgress(percentage);
      }
    };

    xhr.onload = () => {
      let data: any;

      try {
        data = JSON.parse(
          xhr.responseText
        );
      } catch {
        reject(
          new Error(
            "Invalid response from server"
          )
        );
        return;
      }

      if (
        xhr.status >= 200 &&
        xhr.status < 300
      ) {
        onProgress?.(100);

        resolve(data);
      } else {
        reject(
          new Error(
            data?.message ||
              "File upload failed"
          )
        );
      }
    };

    xhr.onerror = () => {
      reject(
        new Error(
          "Network error while uploading the file"
        )
      );
    };

    xhr.onabort = () => {
      reject(
        new Error(
          "File upload was cancelled"
        )
      );
    };

    const formData =
      new FormData();

    formData.append(
      "image",
      file
    );

    xhr.send(formData);
  });
}

async function uploadImagesWithProgress(
  files: File[],
  onProgress?: (progress: number) => void
): Promise<{
  success: boolean;
  urls: string[];
}> {
  if (files.length === 0) {
    return {
      success: true,
      urls: [],
    };
  }

  if (files.length > 4) {
    throw new Error(
      "You can upload a maximum of 4 images"
    );
  }

  const urls: string[] = [];

  for (
    let i = 0;
    i < files.length;
    i++
  ) {
    const file = files[i];

    const result =
      await uploadFileWithProgress(
        file,
        (fileProgress) => {
          /*
           * Convert individual file progress
           * into overall progress.
           *
           * Example:
           * File 1 = 100%
           * File 2 = 50%
           * File 3 = 0%
           *
           * Overall = 50%
           */

          const overallProgress = Math.round(
            ((i * 100) +
              fileProgress) /
              files.length
          );

          onProgress?.(
            overallProgress
          );
        }
      );

    urls.push(result.url);
  }

  onProgress?.(100);

  return {
    success: true,
    urls,
  };
}

/* =========================================================
   ADMIN API
========================================================= */

export const adminApi = {
  /* =======================================================
     AUTH
  ======================================================= */

  login: (
    email: string,
    password: string
  ) =>
    request(
      "/admin/auth/login",
      {
        method: "POST",
        body: JSON.stringify({
          email,
          password,
        }),
      }
    ),

  logout: () =>
    request(
      "/admin/auth/logout",
      {
        method: "POST",
      }
    ),

  getMe: () =>
    request(
      "/admin/auth/me",
      {
        method: "GET",
      }
    ),

  /* =======================================================
     PRODUCTS
  ======================================================= */

  getProducts: () =>
    request(
      "/admin/products",
      {
        method: "GET",
      }
    ),

  createProduct: (
    data: Record<string, any>
  ) =>
    request(
      "/admin/products",
      {
        method: "POST",
        body: JSON.stringify(data),
      }
    ),

  updateProduct: (
    id: string,
    data: Record<string, any>
  ) =>
    request(
      `/admin/products/${id}`,
      {
        method: "PUT",
        body: JSON.stringify(data),
      }
    ),

  deleteProduct: (
    id: string
  ) =>
    request(
      `/admin/products/${id}`,
      {
        method: "DELETE",
      }
    ),

  bulkProductAction: (
    ids: string[],
    action:
      | "activate"
      | "deactivate"
      | "delete"
  ) =>
    request(
      "/admin/products/bulk",
      {
        method: "POST",
        body: JSON.stringify({
          ids,
          action,
        }),
      }
    ),

  /* =======================================================
     IMAGE / MEDIA UPLOAD
  ======================================================= */

  uploadImage: (
  file: File,
  onProgress?: (
    progress: number
  ) => void
): Promise<{
  success: boolean;
  url: string;
}> => {
  return uploadFileWithProgress(
    file,
    onProgress
  );
},

uploadImages: (
  files: File[],
  onProgress?: (
    progress: number
  ) => void
): Promise<{
  success: boolean;
  urls: string[];
}> => {
  return uploadImagesWithProgress(
    files,
    onProgress
  );
},

  /* =======================================================
     CATEGORIES
  ======================================================= */

  getCategories: () =>
    request(
      "/admin/categories",
      {
        method: "GET",
      }
    ),

  createCategory: (
    data: Record<string, any>
  ) =>
    request(
      "/admin/categories",
      {
        method: "POST",
        body: JSON.stringify(data),
      }
    ),

  updateCategory: (
    id: string,
    data: Record<string, any>
  ) =>
    request(
      `/admin/categories/${id}`,
      {
        method: "PUT",
        body: JSON.stringify(data),
      }
    ),

  deleteCategory: (
    id: string
  ) =>
    request(
      `/admin/categories/${id}`,
      {
        method: "DELETE",
      }
    ),

  reorderCategories: (
    orderedIds: string[]
  ) =>
    request(
      "/admin/categories/reorder",
      {
        method: "POST",
        body: JSON.stringify({
          orderedIds,
        }),
      }
    ),

  /* =======================================================
     DISCOUNTS
  ======================================================= */

  /*
   * Get all discounts.
   */
  getDiscounts: () =>
    request<{
      success: boolean;
      discounts: any[];
    }>(
      "/admin/discounts",
      {
        method: "GET",
      }
    ),

  /*
   * Create discount.
   *
   * IMPORTANT:
   *
   * For COUPON:
   *
   * The frontend does NOT generate the code.
   *
   * The backend generates a unique code,
   * checks the database,
   * and returns it.
   */
  createDiscount: (
    data: DiscountPayload
  ): Promise<DiscountResponse> =>
    request<DiscountResponse>(
      "/admin/discounts",
      {
        method: "POST",
        body: JSON.stringify({
          ...data,

          /*
           * Never send a manually entered coupon code.
           *
           * Backend owns coupon generation.
           */
          ...(data.type === "COUPON"
            ? {
                code: undefined,
              }
            : {}),
        }),
      }
    ),

  /*
   * Update discount.
   */
  updateDiscount: (
    id: string,
    data: Partial<DiscountPayload>
  ): Promise<DiscountResponse> =>
    request<DiscountResponse>(
      `/admin/discounts/${id}`,
      {
        method: "PATCH",
        body: JSON.stringify(data),
      }
    ),

  /*
   * Delete discount.
   */
  deleteDiscount: (
    id: string
  ): Promise<{
    success: boolean;
    message: string;
  }> =>
    request(
      `/admin/discounts/${id}`,
      {
        method: "DELETE",
      }
    ),

  /* =======================================================
     REELS
  ======================================================= */

  getReels: () =>
    request(
      "/reels",
      {
        method: "GET",
      }
    ),

  createReel: (
    data: Record<string, any>
  ) =>
    request(
      "/reels",
      {
        method: "POST",
        body: JSON.stringify(data),
      }
    ),

  updateReel: (
    id: string,
    data: Record<string, any>
  ) =>
    request(
      `/reels/${id}`,
      {
        method: "PUT",
        body: JSON.stringify(data),
      }
    ),

  deleteReel: (
    id: string
  ) =>
    request(
      `/reels/${id}`,
      {
        method: "DELETE",
      }
    ),

  /* =======================================================
     CUSTOMERS
  ======================================================= */

  getCustomers: () =>
    request(
      "/admin/customers",
      {
        method: "GET",
      }
    ),

  /* =======================================================
     ORDERS
  ======================================================= */

  getOrders: (
    params?: {
      status?: string;
      search?: string;
    }
  ) => {
    const query =
      new URLSearchParams();

    if (
      params?.status &&
      params.status !== "all"
    ) {
      query.set(
        "status",
        params.status
      );
    }

    if (params?.search) {
      query.set(
        "search",
        params.search
      );
    }

    const qs =
      query.toString();

    return request(
      `/admin/orders${
        qs ? `?${qs}` : ""
      }`,
      {
        method: "GET",
      }
    );
  },

  getOrderById: (
    orderId: string
  ) =>
    request(
      `/admin/orders/${orderId}`,
      {
        method: "GET",
      }
    ),

  updateOrderStatus: (
    orderId: string,
    status: string
  ) =>
    request(
      `/admin/orders/${orderId}/status`,
      {
        method: "PATCH",
        body: JSON.stringify({
          status,
        }),
      }
    ),

  generateOrderManifest: (
    orderId: string
  ) =>
    request(
      `/admin/orders/${orderId}/generate-manifest`,
      {
        method: "POST",
      }
    ),

  generateOrderLabel: (
    orderId: string
  ) =>
    request(
      `/admin/orders/${orderId}/generate-label`,
      {
        method: "POST",
      }
    ),

  printOrderInvoice: (
    orderId: string
  ) =>
    request(
      `/admin/orders/${orderId}/print-invoice`,
      {
        method: "POST",
      }
    ),

  cancelOrder: (
    orderId: string
  ) =>
    request(
      `/admin/orders/${orderId}/cancel`,
      {
        method: "POST",
      }
    ),
};